run:
  # default concurrency is an available CPU number
  concurrency: 4
  # timeout for analysis
  timeout: 5m
  issues-exit-code: 1
  # include test files or not, default is true
  tests: true
  build-tags:
    - integration
  modules-download-mode: vendor

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(gitlab.scorum.com)
  depguard:
    rules:
      main:
        list-mode: lax
        files:
          - $all
        allow:
          - $gostd
  dogsled:
    max-blank-identifiers: 3
  errcheck:
    check-type-assertions: true
    check-blank: false
    exclude-functions:
      - (net/http.ResponseWriter).Write
  exhaustive:
    default-signifies-exhaustive: true
  gocognit:
    min-complexity: 33
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - performance
      - diagnostic
    settings:
      captLocal:
        paramsOnly: true
      hugeParam:
        sizeThreshold: 600
      rangeValCopy:
        sizeThreshold: 600
  gocyclo:
    min-complexity: 23
  gofmt:
    simplify: true
  govet:
    shadow: true
  lll:
    line-length: 250
    tab-width: 4
  misspell:
    locale: US
  nakedret:
    max-func-lines: 40
  nestif:
    min-complexity: 6
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  unparam:
    check-exported: false
  unused:
    check-exported: false

linters:
  fast: false
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - nilerr
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
  disable:
    - cyclop
    - durationcheck
    - errorlint
    - forbidigo
    - forcetypeassert
    - gci
    - gochecknoglobals
    - err113
    - gofumpt
    - gomnd
    - gomoddirectives
    - gosec
    - importas
    - makezero
    - nlreturn
    - noctx
    - paralleltest
    - predeclared
    - promlinter
    - revive
    - tagliatelle
    - testpackage
    - thelper
    - tparallel
    - wastedassign
    - wrapcheck
    - wsl
    - nolintlint

issues:
  exclude-dirs:
    - vendor
  exclude-files:
    - ".*_test.go$"
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - errcheck
        - funlen
        - gochecknoglobals
        - gocritic
        - gocyclo
        - err113
        - gosec
        - lll
        - noctx

    - path: _mock\.go
      linters:
        - gocyclo
        - funlen
        - errcheck
        - dupl
        - gosec
        - gochecknoglobals
        - typecheck

    - linters:
        - govet
      text: "declaration of \"err\" shadows declaration"

    - linters:
        - lll
      text: "^//( )?go:generate "

    - linters:
        - govet
      source: "log := log"

    - linters:
        - gochecknoglobals
      text: "`log` is a global variable$"

    - linters:
        - staticcheck
      source: "choice:\".+\""

    - linters:
        - stylecheck
      text: "ST1000:" #disable at least one file in a package should have a package comment

    - linters:
        - stylecheck
      text: "ST1020:" #disable comment on exported method

  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  new: false
  
